/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `pending` - Pending * `confirmed` - Confirmed * `cancelled` - Cancelled
 */
export const BookingStatusEnum = {
    Pending: 'pending',
    Confirmed: 'confirmed',
    Cancelled: 'cancelled'
} as const;
export type BookingStatusEnum = typeof BookingStatusEnum[keyof typeof BookingStatusEnum];

