/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `active` - Active * `inactive` - Inactive * `completed` - Completed
 */
export const ClassStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Completed: 'completed'
} as const;
export type ClassStatusEnum = typeof ClassStatusEnum[keyof typeof ClassStatusEnum];

