/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LabelEnum } from './labelEnum';


export interface PatchedTeacher { 
    readonly id?: number;
    readonly created_at?: string;
    name?: string;
    bio?: string | null;
    birth?: string | null;
    label?: LabelEnum;
    phone?: string;
    email?: string;
    password?: string;
    img?: string;
    rating?: string;
}
export namespace PatchedTeacher {
}


