/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeEnum } from './typeEnum';
import { ClassStatusEnum } from './classStatusEnum';


export interface PatchedClass { 
    readonly id?: number;
    readonly created_at?: string;
    type?: TypeEnum;
    level?: string;
    description?: string;
    status?: ClassStatusEnum;
    subject?: number;
    teacher?: number;
}
export namespace PatchedClass {
}


