/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleStatusEnum } from './scheduleStatusEnum';


export interface Schedule { 
    readonly id: number;
    readonly created_at: string;
    day_of_week: number;
    start_time: string;
    end_time: string;
    status?: ScheduleStatusEnum;
    class_obj: number;
}
export namespace Schedule {
}


