/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `active` - Active * `inactive` - Inactive
 */
export const ScheduleStatusEnum = {
    Active: 'active',
    Inactive: 'inactive'
} as const;
export type ScheduleStatusEnum = typeof ScheduleStatusEnum[keyof typeof ScheduleStatusEnum];

