/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `upcoming` - Upcoming * `ongoing` - Ongoing * `finished` - Finished * `cancelled` - Cancelled
 */
export const SessionStatusEnum = {
    Upcoming: 'upcoming',
    Ongoing: 'ongoing',
    Finished: 'finished',
    Cancelled: 'cancelled'
} as const;
export type SessionStatusEnum = typeof SessionStatusEnum[keyof typeof SessionStatusEnum];

