/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Student { 
    readonly id: number;
    readonly created_at: string;
    name: string;
    birth?: string | null;
    level?: string;
    phone?: string;
    email: string;
    password: string;
    img?: string;
}

