/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookedTimeSlot { 
    booking_id: number;
    id: number;
    start_at: string;
    end_at: string;
    status: string;
    booking_status: string;
}

