/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookingStatusEnum } from './bookingStatusEnum';
import { Teacher } from './teacher';
import { Student } from './student';
import { TimeSlot } from './timeSlot';


export interface BookingDetail { 
    readonly id: number;
    readonly student: Student;
    readonly time_slot: TimeSlot;
    readonly teacher: Teacher;
    readonly created_at: string;
    status?: BookingStatusEnum;
}
export namespace BookingDetail {
}


