/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `open` - Open * `closed` - Closed * `complete` - Complete * `full` - Full
 */
export const ClassStatusEnum = {
    Open: 'open',
    Closed: 'closed',
    Complete: 'complete',
    Full: 'full'
} as const;
export type ClassStatusEnum = typeof ClassStatusEnum[keyof typeof ClassStatusEnum];

