/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClassRegistrationResponse { 
    success: boolean;
    message: string;
    class_status: string;
    enrolled_students: number;
    created_session_ids?: Array<number>;
    reused_session_ids?: Array<number>;
}

