/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Teacher } from './teacher';
import { ClassStatusEnum } from './classStatusEnum';
import { Subject } from './subject';


export interface ClassDetail { 
    readonly id: number;
    readonly subject: Subject;
    readonly teacher: Teacher;
    readonly created_at: string;
    level?: string;
    max_students?: number;
    description?: string;
    status?: ClassStatusEnum;
}
export namespace ClassDetail {
}


