/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClassStatusEnum } from './classStatusEnum';


export interface Class { 
    readonly id: number;
    readonly created_at: string;
    level?: string;
    max_students?: number;
    description?: string;
    status?: ClassStatusEnum;
    subject: number;
    teacher: number;
}
export namespace Class {
}


