/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `student` - Student * `teacher` - Teacher * `tutor` - Tutor
 */
export const NotificationRoleEnum = {
    Student: 'student',
    Teacher: 'teacher',
    Tutor: 'tutor'
} as const;
export type NotificationRoleEnum = typeof NotificationRoleEnum[keyof typeof NotificationRoleEnum];

