/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationRoleEnum } from './notificationRoleEnum';


export interface PatchedNotification { 
    readonly id?: number;
    role?: NotificationRoleEnum;
    readonly student_id?: number | null;
    readonly teacher_id?: number | null;
    title?: string;
    message?: string;
    is_read?: boolean;
    readonly created_at?: string;
}
export namespace PatchedNotification {
}


