/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookingStatusEnum } from './bookingStatusEnum';


export interface PatchedBooking { 
    readonly id?: number;
    readonly created_at?: string;
    status?: BookingStatusEnum;
    time_slot?: number;
    student?: number;
    class_obj?: number;
}
export namespace PatchedBooking {
}


