/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SessionStatusEnum } from './sessionStatusEnum';


export interface PatchedSession { 
    readonly id?: number;
    readonly created_at?: string;
    start_at?: string;
    end_at?: string;
    status?: SessionStatusEnum;
    recording_url?: string | null;
    recording_public_id?: string | null;
    recording_uploaded_at?: string | null;
    class_obj?: number | null;
    time_slot?: number | null;
    student?: number | null;
    teacher?: number;
}
export namespace PatchedSession {
}


