/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeacherRoleEnum } from './teacherRoleEnum';


export interface PatchedTeacher { 
    readonly id?: number;
    password?: string;
    readonly created_at?: string;
    name?: string;
    bio?: string | null;
    role?: TeacherRoleEnum;
    phone?: string;
    email?: string;
    img?: string | null;
    rating?: string | null;
}
export namespace PatchedTeacher {
}


