/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedStudent { 
    readonly id?: number;
    password?: string;
    readonly created_at?: string;
    name?: string;
    phone?: string;
    email?: string;
    img?: string | null;
}

