/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SessionDetail } from './sessionDetail';


export interface RoomDetail { 
    readonly id: number;
    readonly session: SessionDetail;
    readonly created_at: string;
    room_code: string;
}

