/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Class } from './class';
import { ScheduleStatusEnum } from './scheduleStatusEnum';


export interface ScheduleDetail { 
    readonly id: number;
    readonly class_obj: Class;
    readonly created_at: string;
    day_of_week: number;
    start_time: string;
    end_time: string;
    status?: ScheduleStatusEnum;
}
export namespace ScheduleDetail {
}


