/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SessionStatusEnum } from './sessionStatusEnum';
import { Teacher } from './teacher';
import { Student } from './student';
import { TimeSlot } from './timeSlot';
import { ClassDetail } from './classDetail';


export interface SessionDetail { 
    readonly id: number;
    readonly class_obj: ClassDetail;
    readonly teacher: Teacher;
    readonly time_slot: TimeSlot;
    readonly student: Student;
    readonly created_at: string;
    start_at: string;
    end_at: string;
    status?: SessionStatusEnum;
    recording_url?: string | null;
    recording_public_id?: string | null;
    recording_uploaded_at?: string | null;
}
export namespace SessionDetail {
}


