/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SessionStatusEnum } from './sessionStatusEnum';


export interface Session { 
    readonly id: number;
    readonly created_at: string;
    start_at: string;
    end_at: string;
    status?: SessionStatusEnum;
    class_obj: number;
    teacher: number;
    booking?: number | null;
}
export namespace Session {
}


