/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `tutor` - Tutor * `teacher` - Teacher
 */
export const TeacherRoleEnum = {
    Tutor: 'tutor',
    Teacher: 'teacher'
} as const;
export type TeacherRoleEnum = typeof TeacherRoleEnum[keyof typeof TeacherRoleEnum];

