/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleEnum } from './roleEnum';


export interface Teacher { 
    readonly id: number;
    password: string;
    readonly created_at: string;
    name: string;
    bio?: string | null;
    role: RoleEnum;
    phone?: string;
    email: string;
    img?: string | null;
    rating?: string | null;
}
export namespace Teacher {
}


