/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `available` - Available * `booked` - Booked
 */
export const TimeSlotStatusEnum = {
    Available: 'available',
    Booked: 'booked'
} as const;
export type TimeSlotStatusEnum = typeof TimeSlotStatusEnum[keyof typeof TimeSlotStatusEnum];

