/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeSlotStatusEnum } from './timeSlotStatusEnum';


export interface TimeSlot { 
    readonly id: number;
    readonly created_at: string;
    start_at: string;
    end_at: string;
    status?: TimeSlotStatusEnum;
    teacher: number;
}
export namespace TimeSlot {
}


