/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Teacher } from './teacher';
import { TimeSlotStatusEnum } from './timeSlotStatusEnum';


export interface TimeSlotDetail { 
    readonly id: number;
    readonly teacher: Teacher;
    readonly created_at: string;
    start_at: string;
    end_at: string;
    status?: TimeSlotStatusEnum;
}
export namespace TimeSlotDetail {
}


