/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookedTimeSlot } from './bookedTimeSlot';
import { Student } from './student';


export interface TutorBookedStudent { 
    readonly student: Student;
    time_slots: Array<BookedTimeSlot>;
}

