/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `online` - Online * `offline` - Offline
 */
export const TypeEnum = {
    Online: 'online',
    Offline: 'offline'
} as const;
export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];

