/**
 * EraNux API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UploadRecordingResponse { 
    success: boolean;
    message: string;
    secure_url?: string | null;
    public_id?: string | null;
    session_id?: number | null;
    duration?: number | null;
    bytes?: number | null;
    format?: string | null;
}

