# Generated by Django 4.2.25 on 2025-12-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='max_students',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
