# Generated by Django 4.2.25 on 2026-02-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_teacher_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='recording_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='recording_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='recording_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
