# Generated by Django 4.2.25 on 2026-01-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_teacher_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
